### ISSUE TITLE
Replace YAML files by Database

### ISSUE THREAD

**Issue by matheuswhite** [matheuswhite/bluebees#19]
## Description
Replace YAML files used for data storage by Database

## Tasks
1. [ ] Search the best database that fits into bluebees storage schema
2. [ ] Implement a interface to storage data. This data must be accessed by name and by type (Network, Application, Node, Device, etc)
3. [ ] Replace YAML by selected Database
